### Test GET all notes
GET http://localhost:3000/notes/all
Accept: application/json

### Test POST create note
POST http://localhost:3000/notes/new
Content-Type: application/json

{
  "title": "Test Note",
  "content": "Guess it works."
}

### Test GET note by ID
GET http://localhost:3000/notes/note/3
Accept: application/json

### Test PUT update note
PUT http://localhost:3000/notes/update/1
Content-Type: application/json

{
  "title": "Check updated note",
  "content": "Huh! Still Doubting?!."
}

### Test DELETE note
DELETE http://localhost:3000/notes/delete/2
Accept: application/json
