### Test GET all notes
GET http://localhost:3000/notes/all
Accept: application/json

### Test POST create note
POST http://localhost:3000/notes/new
Content-Type: application/json

{
  "title": "Test Note",
  "content": "Guess it works."
}

### Test GET note by ID
GET http://localhost:3000/notes/note/3
Accept: application/json

### Test PUT update note
PUT http://localhost:3000/notes/update/ebd474c3-7ad5-4244-ad9a-756b16297e7a
Content-Type: application/json

{
  "title": "Check updated note",
  "content": "Huh! Still Doubting?!."
}

### Test DELETE note
DELETE http://localhost:3000/notes/delete/5
Accept: application/json
